### ISSUE TITLE
Konnected will continuously reboot if the network if offline, which makes it pointless to ever buy a Battery Backup.

### ISSUE THREAD

**Issue by trooperthorn** [konnected-io/konnected-security#149]
Issue: Firmware Source is written to fail when the rest of the network if offline.

What happens: Konnected Reboots every 5 minutes if either of the following occur:
- NTP does not connect to hard coded internet URLs.
- failsafe: reboot after 5 minutes in case of extended wifi outage

With the Current Configuration, this leads disable the entire Konnected Ecosystem under the following conditions:
- Loss of Internet Access (cannot resolve NTP to time.google.com or pool.ntp.org results to reboot)
- Loss of DNS (cannot resolve the NTP urls to IP, results in reboot)
- Deatuh attack on wifi. (cannot connect to Wifi, results in reboot)
- Power Outage  (cannot connect to Network, DNS, NTP, resulting in reboot
- DHCP offline (calls DHCP every few minutes, even if the lease is set to 30 days or adjusted down to 7)

File:   konnected-security/src/lfs/wifi.lua

Lines 15-18:
-- failsafe: reboot after 5 minutes in case of extended wifi outage
failsafeTimer = tmr.create()
failsafeTimer:register(300000, tmr.ALARM_SINGLE, function() node.restart() end)

Line 64: 
    sntp.sync({gw, 'time.google.com', 'pool.ntp.org'},

I block all NTP requests leaving the network to stop replay attacks. Once I created DNS records to point to my NTP Server, the connection stayed online.

**Comment by heythisisnate** [comment]
Thanks for the report, @trooperthorn.
Yes, you are correct that the firmware is designed to reboot loop when the network is offline. The idea is that ultimately the network will come back up and the device will automatically reconnect and resume operation when that happens.

You'll notice that the first server in the NTP server list is `gw` (your router/gateway IP) so if you configure your router to respond to NTP, then the NTP request will never leave your network.

It's not pointless to buy a battery backup. If your network/router is also backed-up with a battery, then everything should continue working through a power outage. Our backup battery also works quite well with most consumer grade 12V routers/modems.

The failsafe reboot loop is by design, to allow for the network to recover and the device to reconnect. Did you have any other suggestions for how to mitigate a network failure?
