### ISSUE TITLE
Doesn't play well with wifi extenders

### ISSUE THREAD

**Issue by tailg8nj** [konnected-io/konnected-security#89]
I believe it has to do with device ID strategy.

As seen here, the app will update the corresponding device via dni 
https://github.com/konnected-io/konnected-security/blob/9966fc5f8985bb203b1220aa9ae6ccad03df3210/src/application.lua#L9

However during discovery, if the NodeMCU is connected to certain extenders, it will be assigned a random MAC address. Yet the application still reports on its hardware MAC.

Is there any way to change the ID strategy so that this isn't an issue?

**Comment by heythisisnate** [comment]
This is a known issue and is caused by some wifi-extenders that change the device's MAC address when repeating the signal. We do not have plans to change the ID strategy as this is specified by the SSDP discovery protocol that is used for network discovery. There are a few workarounds:

1. Best option: Don't use WiFi extenders. Use a mesh WiFi network instead to expand wireless coverage.
2. Turn off the wifi extender during discovery.
